- hosts: wordpress

  vars_prompt:

    - name: phpsessid
      prompt: Enter the PHPSESSID that should bypass maintenance mode

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors

    - block:

        - ansible.builtin.template:
            src: .maintenance
            dest: "{{ wp_path }}"

        - ansible.builtin.template:
            src: maintenance.php
            dest: "{{ wp_path }}/wp-content/"

      become: yes
      become_user: www-data
