# ------------------------------------------------------------------------------
# wp-create-site.yml
# ------------------------------------------------------------------------------

# Creates a WordPress site using our default architecture for WordPress sites:
#  - MariaDB database
#  - Apache with the PHP module as a combined web and application layer
#  - A reverse proxy front-end based on Nginx

---

- hosts: localhost

  vars_prompt:

    - name: wp_host
      prompt: Which WordPress host do you want to create a website on?
      private: false

  tasks:

    - ansible.builtin.add_host:
        name: "{{ wp_host }}"
        groups: wp_host
      changed_when: false

    - name: Set a fact containing the name of the selected wp_host
      ansible.builtin.set_fact:
        wp_host: "{{ wp_host }}"

  tags: always

- hosts: wordpress:&wp_host

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors
      tags: always

- name: Configure any required DNS records in our external DNS zone
  hosts: gateway
  tags: dns
  vars:
    wp_host: "{{ hostvars.localhost.wp_host }}"
    dns_record_hostname: "{{ hostvars[wp_host].wp_subdomain }}"
    dns_record_inventory_host: "{{ wp_host }}"

  tasks:

    - block:

        - ansible.builtin.import_role:
            name: dns_api
            tasks_from: create-or-update-address-records

        - ansible.builtin.import_role:
            name: dns_api
            tasks_from: create-or-update-address-records
          vars:
            dns_record_hostname: ''
          when: hostvars[wp_host].wp_subdomain == 'www'

      when: "'external' in hostvars[wp_host].group_names"

    - ansible.builtin.import_role:
        name: dynamic_dns
        tasks_from: create-record
      when: hostvars.localhost.wp_host == 'gateway'

- name: >-
    Delete any temporary DNS mask record that might have been put in place for
    an external WordPress site during a copy operation
  hosts: hub
  tags: dns
  vars:
    wp_host: "{{ hostvars.localhost.wp_host }}"
    wp_server_name: "{{ hostvars[wp_host].wp_server_name }}"

  tasks:

    - ansible.builtin.import_role:
        name: dns
        tasks_from: delete-site.yml
      when: "'external' in hostvars[wp_host].group_names"

- hosts: wordpress:&wp_host

  tasks:

    - ansible.builtin.import_role:
        name: database
        tasks_from: create-site
        handlers_from: none
      # By default the database is co-hosted with WordPress web and application
      # layer. However, if wp_database_host is defined then it will be installed
      # remote from the web and application layer on that host.
      delegate_to: "{{ wp_database_host | default(inventory_hostname) }}"
      tags: database

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: create-site
      tags: wordpress

    - ansible.builtin.import_role:
        name: wordpress_apache
        tasks_from: create-site
      tags: webserver

    - ansible.builtin.import_role:
        name: reverse_proxy
        tasks_from: create-site
      # By default the reverse proxy is co-hosted with WordPress web and
      # application layer. However, if wp_database_host is defined then it will
      # be installed remote from the web and application layer on that host.
      delegate_to: "{{ wp_reverse_proxy_host | default(inventory_hostname) }}"
      tags: proxy
