- hosts: wordpress

  vars_prompt:

    - name: wp_cli_command
      prompt: Enter the command that you want me to run?
      private: no

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors

    - ansible.builtin.shell:
        chdir: "{{ wp_path }}"
        cmd: "wp {{ wp_cli_command }}"
        executable: bash
      register: command_result
      become: yes
      become_user: www-data

    - debug:
        msg: "{{ command_result.stdout }}"
