# ------------------------------------------------------------------------------
# run-wp-cli-script.yml
# ------------------------------------------------------------------------------

---

- hosts: wordpress

  vars_prompt:

    - name: wp_cli_script
      prompt: What WPI CLI script do you want me to run?
      private: no

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors

    - name: Run the requested script against the selected WordPress site
      ansible.builtin.import_role:
        name: wordpress
        tasks_from: run-wp-cli-script
