# ------------------------------------------------------------------------------
# wp-copy-certificate.yml
# ------------------------------------------------------------------------------

---

- name: Prompt for the WordPress host that we are copying from
  hosts: localhost
  gather_facts: false

  vars_prompt:

    - name: from_host
      prompt: What host are we copying from?
      private: false

  tasks:

    - ansible.builtin.add_host:
        name: "{{ from_host }}"
        groups: from_host
      changed_when: false

    - name: Set a fact with the name of the from host
      ansible.builtin.set_fact:
        from_host: "{{ from_host }}"

- name: Fetch the LetsEncrypt full chain and private key from the from host
  hosts: wordpress:&from_host

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors

    - name: Report the subdomain that we are copying from
      debug:
        msg: Copying from subdomain {{ wp_subdomain }} on this host

    - block:

        - name: Stat the fullchain
          stat:
            path: "\
              /etc/letsencrypt/live/{{ wp_server_name }}-0001/fullchain.pem"
            follow: false
          register: fullchain_stat

        - name: Fetch the LetsEncrypt full chain
          ansible.builtin.fetch:
            src: "{{ fullchain_stat.stat.lnk_source }}"
            dest: "/tmp/fullchain.pem"
            flat: true

        - name: Stat the privkey
          stat:
            path: "\
              /etc/letsencrypt/live/{{ wp_server_name }}-0001/privkey.pem"
            follow: false
          register: privkey_stat

        - name: Fetch the LetsEncrypt private key
          ansible.builtin.fetch:
            src: "{{ privkey_stat.stat.lnk_source }}"
            dest: "/tmp/privkey.pem"
            flat: true

      become: yes

- name: Prompt for the WordPress host that we are copying to
  hosts: localhost
  gather_facts: false

  vars_prompt:

    - name: to_host
      prompt: What host are we copying to?
      private: false

  tasks:

    - ansible.builtin.add_host:
        name: "{{ to_host }}"
        groups: to_host
      changed_when: false

- name: Copy the LetsEncrypt full chain and private key to the to host
  hosts: wordpress:&to_host
  vars:
    from_host: "{{ hostvars.localhost.from_host }}"
    wp_subdomain: "{{ hostvars[from_host].wp_subdomain }}"

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: set-site-facts

    - block:

        - name: Copy the LetsEncrypt full chain
          ansible.builtin.copy:
            src: "/tmp/fullchain.pem"
            dest: "/etc/ssl/certs/{{ wp_server_name | replace('.', '_') }}.pem"

        - name: Copy the LetsEncrypt private key
          ansible.builtin.copy:
            src: "/tmp/privkey.pem"
            dest: "\
              /etc/ssl/private/{{ wp_server_name | replace('.', '_') }}.pem"
            mode: u=rw,g=,o=

      become: yes

- hosts: localhost

  tasks:

    - name: Remove the files that we fetched to the controller
      ansible.builtin.file:
        path: "/tmp/{{ item }}.pem"
        state: absent
      loop: ['fullchain', 'privkey']
