# ------------------------------------------------------------------------------
# delete-site.yml
# ------------------------------------------------------------------------------

# Deletes a WordPress site that uses our default architecture for WordPress
# sites:
#  - MariaDB database
#  - Apache with the PHP module as a combined web and application layer
#  - A reverse proxy front-end based on Nginx

---

- hosts: wordpress

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors
      tags: always

    - name: Remove Nginx reverse proxy configuration for the WordPress site
      ansible.builtin.import_role:
        name: reverse_proxy
        tasks_from: delete-site
      # By default the reverse proxy is co-hosted with WordPress web and
      # application layer. However, if wp_database_host is defined then it will
      # have been installed remote from the web and application layer on that
      # host.
      delegate_to: "{{ wp_reverse_proxy_host | default(inventory_hostname) }}"
      tags: proxy

    - name: Remove Apache2 web configuration for the WordPress site
      ansible.builtin.import_role:
        name: wordpress_apache
        tasks_from: delete-site
      tags: webserver

    - name: Remove the WordPress site's configuration
      ansible.builtin.import_role:
        name: wordpress
        tasks_from: delete-site
      tags: wordpress

    - name: "\
        Delete WordPress site database and the database user used to access it"
      ansible.builtin.import_role:
        name: database
        tasks_from: delete-site
        handlers_from: none
      # By default the database is co-hosted with WordPress web and application
      # layer. However, if wp_database_host is defined then it will have been
      # installed remote from the web and application layer on that host.
      delegate_to: "{{ wp_database_host | default(inventory_hostname) }}"
      tags: database

    - block:

        - block:

            - ansible.builtin.include_role:
                name: dns_api
                tasks_from: delete-address-record
              loop: ['A', 'AAAA']
              loop_var: dns_record_type

          when: "'external' in group_names"

        - ansible.builtin.import_role:
            name: dns
            tasks_from: delete-record
          delegate_to: hub
          when: "'internal' in group_names and inventory_hostname != 'gateway'"

        - ansible.builtin.import_role:
            name: dynamic_dns
            tasks_from: delete-record
          vars:
            dns_record_type: A
          when: inventory_hostname == 'gateway'

      vars:
        dns_record_hostname: "{{ wp_subdomain }}"
      tags: dns
