- hosts: wordpress

  tasks:

    - ansible.builtin.import_role:
        name: wordpress
        tasks_from: site-action-precursors

    - block:

        - ansible.builtin.file:
            path: "{{ wp_path }}/.maintenance"
            state: absent

        - ansible.builtin.file:
            path: "{{ wp_path }}/wp-content/maintenance.php"
            state: absent

      become: yes
      become_user: www-data
